language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements_dev.txt"
    - "pip install coveralls"
script:
    - "make test"
after_success:
  coveralls
notifications:
    email:
        recipients:
            - "ellisonleao@gmail.com"
